### ISSUE TITLE
`subfolder` seems broken

### ISSUE THREAD

**Issue by taurr** [cargo-generate/cargo-generate-action#9]
Something has broken.

It should be possible to specify a subfolder , but it doesn't seem to work.

I have a repo with 3 related templates in it. It has been setup to build the generated templates, but the GH action fails, trying to get the user to select a template 😦 

The `subfolder` option has been specified.

https://github.com/taurr/bevy-template-rs/actions/runs/1708208429

part of my workflow:
```yml
  lib_plugin:
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: mytemplate
    steps:
      - uses: actions/checkout@v2
      - name: Expand template
        uses: cargo-generate/cargo-generate-action@v0.11.0
        with:
          name: ${{ env.PROJECT_NAME }}
          subfolder: lib-plugin

      - name: Setup Rust rust-toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Check expanded template
        # we need to move the generated project to a temp folder, away from the template project
        # otherwise `cargo` runs would fail
        # see https://github.com/rust-lang/cargo/issues/9922
        run: |
          mv $PROJECT_NAME ${{ runner.temp }}/
          cd ${{ runner.temp }}/$PROJECT_NAME
          cargo check
```

**Comment by sassman** [comment]
for completeness I attach the build log:

<img width="1396" alt="image" src="https://user-images.githubusercontent.com/329682/149780886-9d03faa5-059f-46c8-a65f-3bf51b369f0b.png">

**Comment by pplmx** [comment]
I'm confused for this configuration.

Here is my config in `0.18.3`

```yml
            -   name: Generate Example from Template
                uses: cargo-generate/cargo-generate-action@v0.18.3
                with:
                    name: ${{ env.PROJECT_NAME }}
                    subfolder: template/cxx
                    template_values_file: .github/workflows/template_values.toml
```

If I want to upgrade to `0.18.5`, how to change it? Could you give me some help? Thanks a lot.

**Comment by pplmx** [comment]
Like this:

```yaml
            -   name: Generate cxx example from template/cxx
                uses: cargo-generate/cargo-generate-action@v0.18.5
                with:
                    name: ${{ env.CXX_PROJECT_NAME }}
                    template: template/cxx
                    arguments: "--template-values-file .github/workflows/template_values.toml --verbose"
```
